"""
user_profile

Revision ID: 602ff85e0f67
Revises: c1cb8f58cf71
Create Date: 2025-05-11 17:38:57.973570
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '602ff85e0f67'
down_revision: str | None = 'c1cb8f58cf71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_profile',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'travel_style',
            sa.Enum('RELAX', 'ADVENTURE', 'CULTURE', 'PARTY', name='user_travel_style_enum'),
            nullable=True,
        ),
        sa.Column(
            'preferred_pace', sa.Enum('CALM', 'MODERATE', 'INTENSE', name='user_travel_pace_enum'), nullable=True
        ),
        sa.Column('budget', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='user_budget_enum'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
