services:
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  prestart:
    build:
      context: ./backend
    command: /app/scripts/prestart.sh
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true

  backend:
    build:
      context: ./backend
    command: ./scripts/start-reload.sh
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:80/api/v1/utils/health-check/" ]
      interval: 1s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://backend:8000
    restart: always
    ports:
      - "5173:5173"
    volumes:
      # Selective mounts for development
      # Source code and assets (frequently changed)
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      
      # Configuration files (occasionally changed)
      - ./frontend/env.d.ts:/app/env.d.ts
      - ./frontend/eslint.config.js:/app/eslint.config.js
      - ./frontend/index.html:/app/index.html
      - ./frontend/openapi-ts.config.ts:/app/openapi-ts.config.ts
      - ./frontend/openapi.json:/app/openapi.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      
      # IMPORTANT: node_modules is NOT mounted from the host
      # It's built into the image to ensure consistent dependency resolution
    env_file:
      - .env
    environment:
      - VITE_BACKEND_URL=http://backend:8000
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
        restart: true

volumes:
  app-db-data:
