// This file is auto-generated by @hey-api/openapi-ts

export type UtilsUtilsViewHealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/utils/health-check'
}

export type UtilsUtilsViewHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: boolean
}

export type UtilsUtilsViewHealthCheckResponse =
  UtilsUtilsViewHealthCheckResponses[keyof UtilsUtilsViewHealthCheckResponses]

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}
